<?php

/*
 * This file is part of the Incipio package.
 *
 * (c) Théo FIDRY <theo.fidry@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace ApiBundle\Doctrine\ORM\Manager;

use ApiBundle\Entity\User;
use FOS\UserBundle\Doctrine\UserManager as BaseUserManager;
use FOS\UserBundle\Model\UserInterface;

/**
 * @author Théo FIDRY <theo.fidry@gmail.com>
 */
class UserManager extends BaseUserManager
{
    /**
     * {@inheritdoc}
     */
    public function deleteUser(UserInterface $user)
    {
        // Unset relations before actually removing the user
        if ($user instanceof User) {
            $jobs = $user->getJobs();
            foreach ($jobs as $job) {
                $job->removeUser($user);
            }
        }

        parent::deleteUser($user);
    }

    /**
     * {@inheritdoc}
     */
    public function updateCanonicalFields(UserInterface $user)
    {
        parent::updateCanonicalFields($user);

        if ($user instanceof User) {
            $user->setOrganizationEmailCanonical($this->canonicalizeEmail($user->getOrganizationEmail()));
        }
    }

    public function updateUser(UserInterface $user, $andFlush = true)
    {
        parent::updateUser($user, $andFlush); // TODO: Change the autogenerated stub
    }
}
